# Generated by Django 3.2 on 2021-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210527_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='real_prise',
            field=models.FloatField(default=0, verbose_name='real price'),
        ),
    ]
