# Generated by Django 3.2 on 2021-06-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210609_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oredermodel',
            options={'verbose_name': 'oreder', 'verbose_name_plural': 'orders'},
        ),
    ]
