# Generated by Django 3.2 on 2021-06-10 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210605_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_oredermodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederModel',
            new_name='OrderModel',
        ),
    ]
