# Generated by Django 3.2 on 2021-06-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordermodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='created_at',
        ),
    ]
