# Generated by Django 3.2 on 2021-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_ordermodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='vaqt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
