# Generated by Django 3.2 on 2021-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordermodel_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='chumo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
