# Generated by Django 3.2 on 2021-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordermodel_chumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='xhumo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
