# Generated by Django 3.2 on 2021-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_ordermodel_xhumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='vaet',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
