# Generated by Django 3.2 on 2021-06-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordermodel_vaet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='chumo',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='vaqt',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='xhumo',
        ),
    ]
