# Generated by Django 3.2 on 2021-06-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210610_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='vaet',
            new_name='created_at',
        ),
    ]
