# Generated by Django 3.2 on 2021-05-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='short_descriptions',
            field=models.TextField(null=True),
        ),
    ]
