# Generated by Django 3.2 on 2021-05-04 03:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_short_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
