# Generated by Django 3.2 on 2021-05-05 08:20

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210505_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttagmodel',
            options={'verbose_name': 'product tag', 'verbose_name_plural': 'product tags'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='short_descriptions',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brandmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.categorymodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
