# Generated by Django 3.2 on 2021-05-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210505_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttagmodel',
            name='tags',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
