# Generated by Django 3.2 on 2021-05-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_producttagmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttagmodel',
            name='tags',
        ),
    ]
