# Generated by Django 3.2 on 2021-05-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productmodel_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='size',
            new_name='sizes',
        ),
    ]
