# Generated by Django 3.2 on 2021-05-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210524_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colormodel',
            old_name='title',
            new_name='code',
        ),
    ]
