# Generated by Django 3.2 on 2021-05-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productmodel_real_prise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='real_prise',
            new_name='real_price',
        ),
    ]
