# Generated by Django 3.2 on 2021-05-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_wishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={},
        ),
    ]
